project:
  type: website

website:
  title: "predicting life expectancy"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: sources.qmd
        text: Sources
      - href: about.qmd
        text: About

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
